name: eeg-gui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - mne
  - openpyxl
  - pip:
      - customtkinter
